version: '3.8'

services:
  datadog-agent:
    image: "gcr.io/datadoghq/agent:latest"
    container_name: datadog-agent
    env_file:
      - ~/sandbox.docker.env # MY API KEY IS STORED IN THIS FILE
    environment:
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_ENV=dev
      - DD_LOG_LEVEL=INFO
      - DD_TAGS="machine:macOSX-docker"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
      - "8126:8126"
      - "8125:8125/udp" # Expose DogStatsD port
    labels:
      com.datadoghq.ad.logs: '[{"source": "datadog-agent", "service": "datadog-agent"}]'
    networks:
      - monitoring

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    networks:
      - monitoring
    environment:
      - REACT_APP_BACKEND_URL=http://backend:80
      - DD_LOGS_INJECTION=true
      - DD_ENV=dev
      - DD_SERVICE=stock-price-frontend
      - DD_VERSION=1.0.0
    labels:
      com.datadoghq.ad.logs: '[{"source": "nodejs", "service": "stock-price-frontend", "log_path": "/app/logs/your-log.log"}]'


  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5261:80"
    networks:
      - monitoring
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_ENV=dev
      - DD_SERVICE=stock-price-api
      - DD_VERSION=1.0.0
      - DD_LOGS_INJECTION=true
      - DD_TRACE_SAMPLE_RATE=1
      - DD_TAGS="machine:macOSX"
    labels:
      com.datadoghq.ad.logs: '[{"source": "csharp", "service": "stock-price-api", "env": "dev, "version": "1.0.0", "sourcecategory": "sourcecode"}]'

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
