name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
    deploy:
        runs-on: self-hosted
        steps:
         # Checkout the code
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set image tag
              run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
            # Build the images
            - name: Build backend
              run: |
                docker build -f Dockerfile.backend \
                  -t stockprice-backend:${{ env.IMAGE_TAG }} .
            - name: Build frontend
              run: |
                docker build -f Dockerfile.frontend \
                  -t stockprice-frontend:${{ env.IMAGE_TAG }} \
                  ./stock-price-frontend
            # Deploy the images
            - name: Deploy
              run: |
                    kubectl set image deployment/stockprice-backend \
                      stockprice-backend=stockprice-backend:${{ env.IMAGE_TAG }} \
                      -n stockprice
                    kubectl set image deployment/stockprice-frontend \
                      stockprice-frontend=stockprice-frontend:${{ env.IMAGE_TAG }} \
                      -n stockprice
                    kubectl set env deployment/stockprice-backend \
                      DD_VERSION=${{ env.IMAGE_TAG }} \
                      -n stockprice
            # Verify the rollout
            - name: Verify rollout
              run: |
                kubectl rollout status deployment/stockprice-backend -n stockprice
                kubectl rollout status deployment/stockprice-frontend -n stockprice